[workspace]
members = [
    "derive",
    "parsing",
    "reflection",
#    "compilation"
]
resolver = "2"

[profile.dev.package."*"]
opt-level = 3

[profile.production]
inherits = "release"
panic = "abort"
strip = true
lto = true
