[package]
name = "leaf_compilation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
half = "2.3.1"
anyhow = "1.0"
tracing = "0.1.40"
leaf_parsing = { path = "../parsing" }
leaf_reflection = { path = "../reflection", features = ["build", "read", "write"] }
